#!/bin/bash
# Copyright David Shin June 18, 2016
#
# Use to add all files, commit and push to github
# Note - Message limited to 9 words
#################################################

git status
git add .
git commit -m "$1 $2 $3 $4 $5 $6 $7 $8 $9"
git push
git status
