#!/bin/bash    
#
# Does google search and opens in your default browser
# Arguments are supplied on the command line
#
search=""
echo "Googling: $@"
for term in $@; do
    search="$search%20$term"
done
open "http://www.google.com/search?q=$search"
