#!/bin/csh
#
# Use this to add "use strict"; to the top of a JavaScript file
#
#
foreach i (*js)
    echo "\"use strict\";" > toto.tmp
    cat toto.tmp $i >> toto2.tmp
    mv toto2.tmp $i
    rm toto.tmp 
end
