#!/usr/bin/env python
"""
Description: Reads the header line of a csv file and prints it to stdout as a list

Usage: csvheader2col.py <file>

Examples: csvheader2col.py file.csv
"""

import csv
import sys

def main():
    with open(sys.argv[1], newline="") as f:
        reader = csv.reader(f)
        header = next(reader)
        for col in header:
            print(col)

if __name__ == "__main__":
   main()
