#!/bin/bash
# Copyright David Shin June 18, 2016
#
# Use to add up to 9 specified files or 
# all files (if no arguments given) 
# to be staged in git
# 
################################################

if [ -z "$1" ] # Checks to see if there is a $1 argument
then 
    git add .
    echo "added all"
else
    git add $1 $2 $3 $4 $5 $6 $7 $8 $9
    echo "added" $1 ", etc. from command line"
fi 
