#!/usr/bin/env python3
"""
File:        json_keys2tree
Created:     2026-01-10
Author:      David Shin

Description:
    Describe what this script does.

Usage:
    json_keys2tree [options] <args>

Examples:
    json_keys2tree --help

Requirements:
    Python 3.9+

Notes:
    Caveats / assumptions / gotchas.
"""

import sys
import json


def main():
    filename = sys.argv[0]
    with open(filename, mode="r", encoding="utf-8") as read_file:
        data = json.load(read_file)
        print(data)

if __name__ == '__main__':
    raise SystemExit(main())
